/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   automaton_transition.c                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ndubouil <ndubouil@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/01/28 22:55:20 by ndubouil          #+#    #+#             */
/*   Updated: 2019/01/28 22:55:57 by ndubouil         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "lexer.h"

/*
**	Ecrire ici rappel des types
*/

int	automaton_transition(int x, int y)
{
	static int automaton[21][16] = {
		{CHAR_STATE,	NUMBER_STATE,	START_STATE,	CHAR_STATE,		BACKSLASH_STATE,			CHAR_STATE,	 		TILDE_STATE, 	DOLLAR_STATE, 	DOTCOMMA_V_STATE, 	PIPE_STATE, 	D_QUOTE_STATE, 		S_QUOTE_STATE, 		LEFT_REDIRECTION_STATE, 		RIGHT_REDIRECTION_STATE, 			AMPERSAND_STATE, 			NONE_STATE},
		{CHAR_STATE,	CHAR_STATE,		STAR_STATE,		CHAR_STATE, 	BACKSLASH_STATE,			EQUAL_STATE,		CHAR_STATE, 	DOLLAR_STATE, 	STAR_STATE, 		STAR_STATE, 	D_QUOTE_STATE, 		S_QUOTE_STATE, 		STAR_STATE, 					STAR_STATE, 						STAR_STATE, 				NONE_STATE},
		{CHAR_STATE,	NUMBER_STATE,	STAR_STATE,		CHAR_STATE, 	BACKSLASH_STATE,			EQUAL_STATE,		CHAR_STATE, 	DOLLAR_STATE, 	STAR_STATE, 		STAR_STATE, 	D_QUOTE_STATE, 		S_QUOTE_STATE, 		LEFT_REDIRECTION_STATE, 		RIGHT_REDIRECTION_STATE, 			STAR_STATE, 				NONE_STATE},
		{CHAR_STATE,	CHAR_STATE,		CHAR_STATE,		CHAR_STATE, 	CHAR_STATE, 				CHAR_STATE,			CHAR_STATE, 	CHAR_STATE, 	CHAR_STATE, 		CHAR_STATE, 	CHAR_STATE, 		CHAR_STATE, 		CHAR_STATE, 					CHAR_STATE, 						CHAR_STATE, 				NONE_STATE},
		{CHAR_STATE,	CHAR_STATE,		STAR_STATE,		CHAR_STATE, 	BACKSLASH_STATE, 			CHAR_STATE,			CHAR_STATE, 	DOLLAR_STATE, 	STAR_STATE, 		STAR_STATE, 	D_QUOTE_STATE, 		S_QUOTE_STATE, 		STAR_STATE, 					STAR_STATE, 						STAR_STATE, 				NONE_STATE},
		{CHAR_STATE,	CHAR_STATE,		STAR_STATE,		CHAR_STATE, 	BACKSLASH_STATE, 			CHAR_STATE,			CHAR_STATE, 	DOLLAR_STATE, 	STAR_STATE, 		STAR_STATE, 	D_QUOTE_STATE, 		S_QUOTE_STATE, 		STAR_STATE, 					STAR_STATE, 						STAR_STATE, 				NONE_STATE},
		{CHAR_STATE,	CHAR_STATE,		STAR_STATE,		CHAR_STATE,		BACKSLASH_STATE,			CHAR_STATE,		TILDE_STATE,	DOLLAR_STATE,	STAR_STATE,			STAR_STATE,		D_QUOTE_STATE,		S_QUOTE_STATE,		STAR_STATE,						STAR_STATE,							STAR_STATE,					NONE_STATE},
		{STAR_STATE,	STAR_STATE,		STAR_STATE,		STAR_STATE, 	STAR_STATE, 				STAR_STATE,			STAR_STATE, 	STAR_STATE, 	STAR_STATE, 		OR_STATE, 		STAR_STATE, 		STAR_STATE, 		STAR_STATE, 					STAR_STATE, 						STAR_STATE, 				NONE_STATE},
		{CHAR_STATE,	CHAR_STATE,		NONE_STATE,		CHAR_STATE, 	BACKSLASH_STATE, 			CHAR_STATE,			NONE_STATE, 	DOLLAR_STATE, 	NONE_STATE, 		NONE_STATE, 	NONE_STATE, 		NONE_STATE, 		NONE_STATE, 					NONE_STATE, 						AND_STATE, 					NONE_STATE},
		{STAR_STATE,	STAR_STATE,		STAR_STATE,		STAR_STATE, 	STAR_STATE,					STAR_STATE,			STAR_STATE, 	STAR_STATE, 	STAR_STATE, 		NONE_STATE, 	STAR_STATE, 		STAR_STATE, 		STAR_STATE, 					STAR_STATE, 						STAR_STATE, 				NONE_STATE},
		{STAR_STATE,	STAR_STATE,		STAR_STATE,		STAR_STATE, 	STAR_STATE, 				STAR_STATE,			STAR_STATE, 	STAR_STATE, 	STAR_STATE, 		NONE_STATE, 	STAR_STATE, 		STAR_STATE, 		STAR_STATE, 					STAR_STATE, 						NONE_STATE, 				NONE_STATE},
		{D_QUOTE_STATE,	D_QUOTE_STATE,	D_QUOTE_STATE,	D_QUOTE_STATE, 	BACKSLASH_D_QUOTE_STATE,	D_QUOTE_STATE,		D_QUOTE_STATE, 	DOLLAR_STATE, 	D_QUOTE_STATE, 		D_QUOTE_STATE, 	END_D_QUOTE_STATE, 	D_QUOTE_STATE, 		D_QUOTE_STATE, 					D_QUOTE_STATE, 						D_QUOTE_STATE, 				NONE_STATE},
		{S_QUOTE_STATE,	S_QUOTE_STATE,	S_QUOTE_STATE,	S_QUOTE_STATE, 	S_QUOTE_STATE, 				S_QUOTE_STATE,		S_QUOTE_STATE, 	S_QUOTE_STATE, 	S_QUOTE_STATE, 		S_QUOTE_STATE, 	S_QUOTE_STATE, 		END_S_QUOTE_STATE, 	S_QUOTE_STATE, 					S_QUOTE_STATE, 						S_QUOTE_STATE, 				NONE_STATE},
		{CHAR_STATE,	NUMBER_STATE,	STAR_STATE,		CHAR_STATE, 	BACKSLASH_STATE, 			CHAR_STATE,			CHAR_STATE, 	DOLLAR_STATE, 	STAR_STATE, 		STAR_STATE, 	D_QUOTE_STATE, 		S_QUOTE_STATE, 		STAR_STATE, 					STAR_STATE, 						STAR_STATE, 				NONE_STATE},
		{CHAR_STATE,	NUMBER_STATE,	STAR_STATE,		CHAR_STATE, 	BACKSLASH_STATE,			CHAR_STATE, 		CHAR_STATE, 	DOLLAR_STATE, 	STAR_STATE, 		STAR_STATE, 	D_QUOTE_STATE, 		S_QUOTE_STATE, 		STAR_STATE, 					STAR_STATE, 						STAR_STATE, 				NONE_STATE},
		{D_QUOTE_STATE,	D_QUOTE_STATE,	D_QUOTE_STATE,	D_QUOTE_STATE, 	D_QUOTE_STATE, 				D_QUOTE_STATE,		D_QUOTE_STATE, 	D_QUOTE_STATE, 	D_QUOTE_STATE, 		D_QUOTE_STATE, 	D_QUOTE_STATE, 		D_QUOTE_STATE, 		D_QUOTE_STATE, 					D_QUOTE_STATE, 						D_QUOTE_STATE, 				NONE_STATE},
		{STAR_STATE,	STAR_STATE,		STAR_STATE,		STAR_STATE,		STAR_STATE, 				STAR_STATE,			STAR_STATE, 	STAR_STATE, 	STAR_STATE, 		STAR_STATE, 	STAR_STATE, 		STAR_STATE, 		DOUBLE_LEFT_REDIRECTION_STATE, 	NONE_STATE, 						LEFT_AGGREGATION_V_STATE, 	NONE_STATE},
		{STAR_STATE,	STAR_STATE,		STAR_STATE,		STAR_STATE, 	STAR_STATE, 				STAR_STATE,			STAR_STATE, 	STAR_STATE, 	STAR_STATE, 		STAR_STATE, 	STAR_STATE, 		STAR_STATE, 		NONE_STATE, 					DOUBLE_RIGHT_REDIRECTION_STATE, 	RIGHT_AGGREGATION_V_STATE, 	NONE_STATE},
		{STAR_STATE,	STAR_STATE,		STAR_STATE,		STAR_STATE, 	STAR_STATE, 				STAR_STATE,			STAR_STATE, 	STAR_STATE, 	STAR_STATE, 		STAR_STATE, 	STAR_STATE, 		STAR_STATE, 		NONE_STATE, 					NONE_STATE, 						STAR_STATE, 				NONE_STATE},
		{STAR_STATE,	STAR_STATE,		STAR_STATE,		STAR_STATE, 	STAR_STATE, 				STAR_STATE,			STAR_STATE, 	STAR_STATE, 	STAR_STATE, 		STAR_STATE, 	STAR_STATE, 		STAR_STATE, 		NONE_STATE, 					NONE_STATE, 						STAR_STATE, 				NONE_STATE}
	};

	return (automaton[x][y]);
}
